version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./devops/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./backend/src:/usr/src/app/src

  redis:
    image: redis:5
    ports:
      - '6379:6379'

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}

volumes:
  mongodb:
