version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./devops/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./backend/src:/usr/src/app/src

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
      - ./backend/devops/mongodb-setup.js:/mongodb-setup.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=test

volumes:
  mongodb:
